services:
  aidbfree:
    image: container-registry.oracle.com/database/free:latest
    container_name: aidbfree
    hostname: aidbfree
    environment:
      - ORACLE_PWD=${ORACLE_PWD}
    ports:
      - "1521:1521"
    restart: always
  